### ISSUE TITLE
Unique object IDs

### ISSUE THREAD

**Issue by xiaoxianma** [bitcart/bitcart#221]
**Is your feature request related to a problem? Please describe.**
Currently, rest APIs return integer id as its object id. For security and other concerns, we decide to replace integer ID with string UID

Scopes:
- Add one more column string UID in all DB tables
- Alter API layer ID to string UID
- Update REST API using integer ID:
    https://github.com/bitcartcc/bitcart/blob/7f8e449e53f366ab3bfbc06108f793a06a554013/api/views/wallets.py#L12
    https://github.com/bitcartcc/bitcart/blob/7f8e449e53f366ab3bfbc06108f793a06a554013/api/views/stores.py#L8 
    https://github.com/bitcartcc/bitcart/blob/master/api/views/websocket.py

**Comment by MrNaif2018** [comment]
We have to decided to just change column type of primary key id column to String type, which is the easiest and the best way we have found so far
