### ISSUE TITLE
[BUG] ERC20 tokens show "ETH" as name in checkout demo

### ISSUE THREAD

**Issue by CherryDT** [bitcart/bitcart#295]
**Describe the bug**
In the store demo, paying with e.g. USDT shows ETH but with USDT price.

**To Reproduce**

1. Go to https://store.bitcartcc.com/
2. Add item to cart, continue to checkout
3. Select "USDT (1)" (which by the way isn't very descriptive either, should be "USDT (ERC20)" or something like that)
4. See incorrect and confusing currency labels

**Expected behavior**
I expect to see "1 **USDT** = $1.00" and "Waiting for 5.000002 **USDT** payment"

**Screenshots**
![image](https://user-images.githubusercontent.com/6010463/177536888-81871117-b1ca-4759-b455-134eef2a15c6.png)

**Comment by MrNaif2018** [comment]
Thanks for your bug report! Indeed, with addition of contracts the naming scheme changed a bit, and while the admin panel was updated, the store was not. Thanks, it will be fixed soon

**Comment by MrNaif2018** [comment]
![изображение](https://user-images.githubusercontent.com/39452697/177584404-0c41cf48-85f4-4f3b-b094-c935f7a881ae.png)

Thanks! Fixed by bitcartcc/bitcart-store@a2d59024f0f229ba3c41f73cd0d7d379b5c11e47
