### ISSUE TITLE
[FEATURE] Adding fiat amount to invoice

### ISSUE THREAD

**Issue by StevenWilliams** [bitcart/bitcart#303]
Including the fiat amount of the invoice could make it more user friendly and make it easier to spot potential billing issues.

**Comment by MrNaif2018** [comment]
Do you mean in the checkout UI?

**Comment by StevenWilliams** [comment]
Yes. It shows the exchange rate and the crypto amount right now. Adding the fiat amount should be shown as well.

https://1428585068-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/assets%2F-Lz8A22xAOkwN-WbWyqG%2F-MPdwCwW0aJvtJKzTAJn%2F-MPeSYoRqiWCvua6xYec%2Ffull_checkout.png?alt=media&token=8d820344-00c1-408e-92ad-3f700d0f22d6

**Comment by MrNaif2018** [comment]
I see, it's more to our UIs. We will do a community poll I guess. You can join our communities to participate (:

**Comment by MrNaif2018** [comment]
Oh, almost forgot it, it was already implemented in version 0.6.10.0!
