### ISSUE TITLE
Add tests for hcaptcha integration

### ISSUE THREAD

**Issue by MrNaif2018** [bitcart/bitcart#314]
As we've recently gained hcaptcha support, it would be good to run tests in a staging environment

Relevant code:
https://github.com/bitcartcc/bitcart/blob/4a6021a0e950f29f9963f54d92f44ae604b58ac7/api/views/token.py#L74-L84
Docs:
https://docs.hcaptcha.com/#integration-testing-test-keys

**Comment by idrissbellil** [comment]
I opened https://github.com/bitcart/bitcart/pull/360

**Comment by MrNaif2018** [comment]
Tests were added by #360, but for some reason PR was closed. I manually merged them, also now adapting for new captcha type
