### ISSUE TITLE
[FEATURE] Odoo Integration

### ISSUE THREAD

**Issue by TheNexter** [bitcart/bitcart#322]
**Is your feature request related to a problem? Please describe.**
https://www.odoo.com/fr_FR/app/ecommerce

**Describe alternatives you've considered**
https://github.com/monero-integrations/moneroodoo

**Comment by MrNaif2018** [comment]
Hi! Could you describe it in more details? Do you mean something like a plugin we have for whmcs, spotify etc, but for odoo?

**Comment by MrNaif2018** [comment]
If it's because it is opensource, we have support for boxbilling/fossbilling too if you need it

**Comment by TheNexter** [comment]
> Hi! Could you describe it in more details? Do you mean something like a plugin we have for whmcs, spotify etc, but for odoo?

Hi ;)

Yes exactly ;)

Odoo is growing fast recently, they provide so many services open source. It's just a suggestion ;)
Odoo is more like internal tool for almost anythings with website builder than just a simple website builder only ;)

Sorry for my english :_)

**Comment by MrNaif2018** [comment]
Resolved
https://github.com/bitcartcc/bitcart-odoo
https://youtu.be/9vorewcOBgE

**Comment by TheNexter** [comment]
So fast 😂 Thx men 😵
