### ISSUE TITLE
[BUG] acme-companion verify error

### ISSUE THREAD

**Issue by Drabuna** [bitcart/bitcart#334]
**Describe the bug**
When deploying the latest version through the configurator, getting the following error from `acme-companion`:
```
Pending
Pending
Pending
Verify error:IP: Invalid response from http://domain.com/.well-known/acme-challenge/aYS8DDlL3oCFaNUlAGFRtYphdX1wY8_Y9hGugoBpNd8: 404
Please check log file for more details: /dev/null
```

**Expected behavior**
I assume the certificate should issue normally.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.2 LTS
- Version: what config is giving me, I assume it's master, yes.

**Additional context**
Tried bumping the version to `nginxproxy/acme-companion:2.2.6`, that didn't help.

**Comment by MrNaif2018** [comment]
Hi! Most likely it's not because of acme-companion or anything. Maybe you didn't configure DNS records?

**Comment by Drabuna** [comment]
Yeah, you are correct!
During the second step of the configurator, I entered a full URL like: "https://domain.com", which caused all the problems.
Had to change it, and re-run the setup. Everything works now, thanks!
Might be a good idea to change the validation in the configuration step, or show an example of how the domain should be entered.

**Comment by MrNaif2018** [comment]
I think it should have warned about DNS validation or something? Or maybe DNS validation worked even with full URL?
