### ISSUE TITLE
[FEATURE] Disable the store/market view

### ISSUE THREAD

**Issue by Drabuna** [bitcart/bitcart#335]
**Is your feature request related to a problem? Please describe.**
I want to use `bitcart` as a payment-only solution - I will generate an invoice via the API, and show the `pay the invoice view` to the user, but the actual products/services will be defined outside of `bitcart`.
When I create a store, and the user navigates to the payment domain he will see something like this:
![image](https://user-images.githubusercontent.com/54286/222969588-38574a61-681b-434d-a086-8cfadd9cda88.png)
Is it possible to show something else on this page (like a custom HTML view), or just disable it altogether?

**Describe the solution you'd like**
Being able to override or disable the `market` view.
Most likely should be possible with some `nginx` config.

**Additional context**
Didn't find anything in the docs.

**Comment by MrNaif2018** [comment]
Use either:
1.
```
export BITCART_INSTALL=backend
export BITCART_ADDITIONAL_COMPONENTS=admin
```
or
2.
`export BITCART_EXCLUDE_COMPONENTS=store`
