### ISSUE TITLE
multiple Shops / POS on different URLs

### ISSUE THREAD

**Issue by skeutmeier** [bitcart/bitcart#337]
**Is your feature request related to a problem? Please describe.**
I would like to have multiple POS on different URLs.
For example, 1 main Shop (like it is now), and other shops reachable under example.com/[user]/[shopname] or something like that.
Would that be possible?

**Comment by MrNaif2018** [comment]
You can access any store via yourstore.com/store/storeid. Would that be enough?

**Comment by skeutmeier** [comment]
oh nice. didnt find this in the docs.

Thanks
