### ISSUE TITLE
[FEATURE] Disable action buttons depending on the status

### ISSUE THREAD

**Issue by Drabuna** [bitcart/bitcart#340]
**Is your feature request related to a problem? Please describe.**
I'm working with Tron main net, and USDT (TRC-2). Pretty sure that this will apply to other cryptos as well.
For example in Payouts, when you select one payout and click `Actions`, you see all the buttons enabled and clickable.
I would think there should be a disabled state for some of them depending on the status of the payout.
The same goes for invoices.

**Describe the solution you'd like**
Disable/enable action buttons depending on the status of the transaction.

**Comment by MrNaif2018** [comment]
Well it's intentional. You can actually retry a payout (even a sent one), by making it cancelled and sending again. It's useful in some cases
