### ISSUE TITLE
[BUG]After clicking the API KEY column, the key would be copied as a shorter string.

### ISSUE THREAD

**Issue by fintechee** [bitcart/bitcart#341]
Hi Alex,

I found a new bug in v0.7.3, this bug didn't exist in the older versions, such as 0.6x.

Describe the bug
After clicking the API KEY column, the key would be copied as a shorter string.

To Reproduce
On the API panel, for example, if the key is "abcdefghijklmnopqrstuvwxyz", because it's very long, so it will be shown as "abcdefghijklmnop...".
Then I clicked the key, the copied string would be the same as it is shown: "abcdefghijklmnop...".
The correct string copied should have been "abcdefghijklmnopqrstuvwxyz".

Bitcartcc Version:
0.7.3

Server:

    OS: Ubuntu 20.04(self-hosted)
    Version 20.04

**Comment by MrNaif2018** [comment]
It's in profile page, right? I can't reproduce, it copies full key for me /:
Which browser do you use?

**Comment by fintechee** [comment]
firefox, API KEYS panel
v0.6.x was correct.

**Comment by MrNaif2018** [comment]
I use firefox too. Really weird. Could you please record a reproduction video?
Another thing to try might be to clear browser cache

**Comment by fintechee** [comment]
I knew the reason now.
I didn't right-click to choose the paste menu item, I tried with the middle button of my mouse.
Then you can reproduce it.
If I use paste menu item or ctrl-v to paste it, then the string would be correct.

**Comment by MrNaif2018** [comment]
I mean you should click with left mouse button to copy :D

**Comment by fintechee** [comment]
Yeah :)
Okay, it's solved, Thank you, bro.
But I recommend you paste the complete string if clicking the middle button of mouse.
I think 80% users will try like me.
I left-click the cell and mid-click to paste it.

**Comment by MrNaif2018** [comment]
Well no, we probably can't handle it. Because we render shrinked text, but on click we execute custom action to copy full data
Middle mouse button focuses over text. I will check though, maybe we can override this one too

**Comment by fintechee** [comment]
No problem, bro!
