### ISSUE TITLE
Donation Link / Create Invoice with no Amount set

### ISSUE THREAD

**Issue by skeutmeier** [bitcart/bitcart#344]
**Is your feature request related to a problem? Please describe.**
I would like to see the possibility (via Webinterface and API) to create an Invoice with no amount set.

**Describe the solution you'd like**
So that the customer (donator) can pay / donate a amount of his liking.

**Comment by MrNaif2018** [comment]
Hi! As written in invoice creation dialog, you just set price of 0 to accept any amount
