### ISSUE TITLE
create a Invoice with 2 or more outputs (+change)

### ISSUE THREAD

**Issue by skeutmeier** [bitcart/bitcart#345]
I would like to see a feature, so that I can create an Invoice though the API, but split the outputs to 2 or more wallets.

Imagine a Shop where you want to publicly traceable donate a percentage of your sales for a good cause. Like 10% of every payment made is directly sent to the wallet of good cause.

Another use case would be a external provider that offers a service and can be paid a fee, directly, on every purchase.
I would really like to see that feature.

**Comment by MrNaif2018** [comment]
The way blockchain works we can't make users send to multiple addresses at once, so it's the postprocessing step. You can use payouts feature for that
