### ISSUE TITLE
[BUG] Monero (XMR) now shows the real balance

### ISSUE THREAD

**Issue by HaziFlorinMarian** [bitcart/bitcart#369]
**Describe the bug**
At moment A I've added all my wallets.
At moment B someone paid with XMR
At moment C money arrived into my wallet (verified with Monero GUI) but the admin interface still shows 0.00 Balance (even after 24h when the transaction is cleared)

**Expected behavior**
At least after a while, to see the balance also from XMR network (I can confirm that it works fine with LTC/BTC/BCH)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Debian 12
- Version latest on 25th September 20223

**Additional context**

**Comment by MrNaif2018** [comment]
That is expected
Balance and payouts aren't currently supported on XMR because we found no way to do it using node RPC only
+balance would not be fully accurate if using only the viewonly part
