### ISSUE TITLE
[FEATURE] Add Turnstile captcha?

### ISSUE THREAD

**Issue by dhana-exe** [bitcart/bitcart#378]
**Is your feature request related to a problem? Please describe.**
Maybe you can add turnstile captcha?

**Describe the solution you'd like**
as far as i know, turnstile captcha (by cloudflare) it's better ones since they didn't require we to solve any puzzle, just click the checkbox and no searching head or toe of some picture.....

**Comment by MrNaif2018** [comment]
Do you think it's better than google recaptcha? Clicking on those images annoys me as well, apparently hcaptcha free plan does not have a silent mode

**Comment by dhana-exe** [comment]
> Do you think it's better than google recaptcha? Clicking on those images annoys me as well, apparently hcaptcha free plan does not have a silent mode

bruh i literally said TURNSTILE not hcaptcha.....
turnstile is owned by cloudflare... they had no image verification at all even on the suspected bot... they just ask you to click the checkbox....

i never talking about hcaptcha even once here

Edit: after i made quick search idk why somehow hcaptcha shown in my result so sorry if you think my comment too harsh
btw if you want to see how it's goes
you should make sure that you type the correct ones... TURNSTILE instead any captcha to prevent some random hcaptcha from showing up XD

just keep in mind that i mean turnstile from cloudflare instead hcaptcha

**Comment by MrNaif2018** [comment]
Why I told about hcaptcha is because it is already integrated into bitcart, but clicking images annoys me, that's why I asked
So I want to choose what to do:
either hcaptcha but find out how to remove images, but I think it's a paid feature 
or google recaptcha
or cloudflare turnstile one

**Comment by dhana-exe** [comment]
> Why I told about hcaptcha is because it is already integrated into bitcart, but clicking images annoys me, that's why I asked So I want to choose what to do: either hcaptcha but find out how to remove images, but I think it's a paid feature or google recaptcha or cloudflare turnstile one

now i really confused....

for hcaptcha... no way you can get rid of clicking image...
but for turnstile cloudflare
no where you will click image... since they had no system like that....

that's why i suggesting they to add cloudflare turnstile instead other captcha (include recaptcha and hcaptcha)
they booth annoying....
that's why i suggesting turnstile on here

**Comment by MrNaif2018** [comment]
I will check all options and implement it in the following few weeks

**Comment by dhana-exe** [comment]
> I will check all options and implement it in the following few weeks

whoa thanks alot xD
and yeah that's all i can tell to you... from the moment i switch using turnstile captcha (cloudflare) from hcaptcha
not single times i seen any clicking random image etc... the most far i can get is just click checkbox button 2-3 times until it's completed.... so yeah
no single "image verification" that will scare the visitor/buyer/user

**Comment by MrNaif2018** [comment]
Okay I added it in #407, still waiting for community feedback, but I love it! It's so much simpler really

**Comment by dhana-exe** [comment]
> Okay I added it in #407, still waiting for community feedback, but I love it! It's so much simpler really

sure sure XD
i already use it for few times and it's the best captcha now XD
maybe if you want to add some more protection
binding turnstile with any PoW verification system will help more
but just this i think already more than enough

**Comment by MrNaif2018** [comment]
Done! You can check it out how it works on the demo or update from master
