### ISSUE TITLE
[BUG] USDT TRX Payment sometimes do not get processed

### ISSUE THREAD

**Issue by ahubertus44** [bitcart/bitcart#389]
**Describe the bug**
Hello, I've setup the bitcart (full) version via the configuration.
I also added multiple currencies like btc, ltc, trx, eth etc ...
My shop is a bit crowded and most customers by with USDT - TRX.
90% of payments made, get the status set to paid then complete
But rarely 10% of invoices created (customers also paid the correct amount to the correct receiving wallet) get stuck at pending.
There is no status change.
I do have multiple payments on the same day with the same price, for example 6.442000 USDT.

**To Reproduce**
I don't know how to reproduce it, it happens so rarely?

**Expected behavior**
The payment made should be recognized by bitcart.

**Comment by g00g1** [comment]
Do you have any more details on this issue? I suspect some of your customer use cryptocurrency exchanges (like binance, telegram wallet etc), and they have one major issue - their funds withdrawals have source address which is not what your customer sees.

Why that matters? Well, [ETH-based coins (like TRX) is complex and here is why](https://t.me/bitcart/20791)...

**Comment by MrNaif2018** [comment]
That is most likely the case indeed, thanks for answering the issue (:
@ahubertus44 if you still have the issue let us know, closing for now
