### ISSUE TITLE
https://admin.bitcart.ai/login testnet connection not working

### ISSUE THREAD

**Issue by dev2021-ctrl** [bitcart/bitcart#391]
I am using this demo https://admin.bitcart.ai/login portal to create eth wallet and using that wallet adddress to add some amount using https://sepoliafaucet.com/ but cannot see the balance credited here https://admin.bitcart.ai/login
Is this expected?
If yes can you suggest some way to use testnet and once tested to integrate the bitcart on my live eccommerce site
![Screenshot from 2024-01-03 02-17-36](https://github.com/bitcart/bitcart/assets/83241464/a6a488b4-fc7f-4bb0-a305-e6740376ed72)

**Comment by MrNaif2018** [comment]
https://testnet.bitcart.ai/

**Comment by dev2021-ctrl** [comment]
this  site https://testnet.bitcart.ai/ not working ,any restriction on this
site

**Comment by MrNaif2018** [comment]
No, it does load for me, although a bit slower than usual, but might be my network

**Comment by dev2021-ctrl** [comment]
ping also not working , seems it does not have any mapping , are u using
specific nameserver
attached images

**Comment by MrNaif2018** [comment]
ah well, it's cache on my end. I guess yeah, it's down. I will investigate

**Comment by dev2021-ctrl** [comment]
thanks ,also I want to integrate the checkout page in my ecommerce site. Is
there readily available frontend bitcart code that handles payment page and
then callback url similar to integration of paypal .
The js code present here will be sufficient for receiving eth payments and
then redirecting https://docs.bitcart.ai/integrations/custom-integration ?

**Comment by dev2021-ctrl** [comment]
Any luck with this https://testnet.bitcart.ai/ , sorrry but need for some urgent testing

**Comment by MrNaif2018** [comment]
testnet.bitcart.ai now back up
