### ISSUE TITLE
Invoices api failing when invoice are more than 36 invoices

### ISSUE THREAD

**Issue by dev2021-ctrl** [bitcart/bitcart#392]
Error: 500 internal server error 

Attached image

This is happening on my prod eth server , pls advise how to debug and resolve it asap.
Rest all api working fine.
![Screenshot from 2024-01-06 19-16-48](https://github.com/bitcart/bitcart/assets/83241464/8ef7c8c0-04a0-41c7-818f-a107a146c6ff)

**Comment by dev2021-ctrl** [comment]
No changes made on the server , it stopped working by itself

**Comment by ilyakonovalenko** [comment]
I noticed some issue with invoices endpoint as well. It creates invoice but never responds back. Docker containers restart helps, but it happens too often with no reason.

**Comment by MrNaif2018** [comment]
It's because of LTC most likely. Please join our community chat, we are performing a big investigation and also posted some temp fixes recently
