### ISSUE TITLE
[BUG] -1 Amount Fails With ETH

### ISSUE THREAD

**Issue by mindhunter77** [bitcart/bitcart#403]
**Describe the bug**
When doing a payout with ETH and selecting -1 for the amount, it fails everytime.

**To Reproduce**

Just do a new payout with ETH and select -1 as the amount.

**Expected behavior**
To send all available funds minus fees.

**Desktop (please complete the following information):**

- OS: Ubuntu Linux (server)
- Client: Windows 10
- Version 0.8.0.0

**Comment by MrNaif2018** [comment]
Thanks for report! It was broken in both eth and tokens. Fixed in d303d90f6d6c2a998ebd7fa71e77e039b1ff2d3b
