### ISSUE TITLE
[BUG] Problem with local deployment

### ISSUE THREAD

**Issue by prograchy** [bitcart/bitcart#413]
**Describe the bug**
I have a problem with local deployment. When I create a docker on https://admin.bitcart.ai/configurator and setup on my machine, then I can just access to bitcart.local/api but I cannot access to admin panel or store.

**To Reproduce**

1. Get configuration codes from https://admin.bitcart.ai/configurator
     - Manual
     - Domain: bitcart.local and HTTPS disabled
     - Coins: Bitcoin
     - Tor support: disabled
     - Installation pack : all

2. Copy the given codes and run on the terminal.
3. Try to access http://bitcart.local/admin and fail.
3.1 - It's just able to access http://bitcart.local/api

**Expected behavior**
On third step it should be able to connect admin panel as the documentation said. 

**Screenshots**
![Uploading bircart-1.png…]()
![Uploading bitcart2.png…]()

**Desktop (please complete the following information):**

- OS: Debian/Linux
- Version : 12

**Additional context**
When I tried to do it like in documentation https://docs.bitcart.ai/deployment/local , then I have still same issue.

**Comment by DaveLess13** [comment]
i have exactly the same problem !

**Comment by MrNaif2018** [comment]
Hi, so if local failed, did
`export BITCART_HOST=127.0.0.1`
help maybe?

**Comment by MrNaif2018** [comment]
I'm assuming the issue is fixed, if not, please join our community chats
