### ISSUE TITLE
Anyway to install if Docker and Docker-Compose are already installed?

### ISSUE THREAD

**Issue by mikekay1** [bitcart/bitcart#422]
I dont want to run the whole setup.sh because of other containers that are already running, I also have a reverse proxy with wildcard domain certificate. Is bitcart compatible in this deployment scenario?

**Comment by MrNaif2018** [comment]
```
export BITCART_REVERSEPROXY=none
./setup.sh
```
Then you can configure it however you like with your own reverse proxy. Also if you don't have your reverse proxy already running, it does not interfere with running containers in any way
For more support please join our official community chats
