### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by therealdogimed** [bitcart/bitcart#430]
**Describe the bug**

unable to create an admin account.

**To Reproduce**

installed using
sudo su -
apt-get update && apt-get install -y git
if [ -d "bitcart-docker" ]; then echo "existing bitcart-docker folder found, pulling instead of cloning."; git pull; fi
if [ ! -d "bitcart-docker" ]; then echo "cloning bitcart-docker"; git clone https://github.com/bitcart/bitcart-docker bitcart-docker; fi
export BITCART_HOST=.local
export BITCART_REVERSEPROXY=nginx
export BITCART_CRYPTOS=btc
export BTC_LIGHTNING=True
export BITCART_ADDITIONAL_COMPONENTS=tor
cd bitcart-docker
./setup.sh

navigate to localhost/admin/register
enter user information
click create account
nothing happens.
**Expected behavior**
i should be able to create an account?
**Screenshots**

**Desktop (please complete the following information):**

- OS: ubuntu server 20.04
- Version [master branch]

**Additional context**

**Comment by MrNaif2018** [comment]
Hi, was your issue resolved? for example BITCART_HOST needed to be bitcart.local, not just .local

**Comment by MrNaif2018** [comment]
If the issue was not fixed, please ask again in our community chats
