### ISSUE TITLE
Update required for Polygon POS network token migration from MATIC to POL

### ISSUE THREAD

**Issue by darkrideroffate** [bitcart/bitcart#434]
**Describe the bug**
Polygon has recently migrated its native token from MATIC to POL, but Bitcart has not yet integrated this change. This could potentially impact users transacting on the Polygon network. Please update Bitcart to support the new native token.

the problem occurs when you try to make a payment using bitcart on matic, bitcart never registers that the POL payment happened because it's still listening to MATIC
For more details, you can refer to the official announcement here:
[Polygon MATIC to POL Migration Announcement](https://polygon.technology/blog/matic-to-pol-migration-is-now-live-everything-you-need-to-know)

**To Reproduce**

1. Go to the admin panel of bitcart and navigate to the wallets section
2. open the wallet creation dialog and type anything in the name, set the currency to matic and set the address to anything
3. create the wallet 
4. you'll see that the wallet is indeed matic
5. Try to make an invoice with the registered wallet and pay it
6. bitcart never reads the transaction and times out

**Comment by MrNaif2018** [comment]
I always thought that it's just a name change and existing RPCs and stuff won't change. Are you sure it affects processing? Will re-check

**Comment by MrNaif2018** [comment]
![изображение](https://github.com/user-attachments/assets/3ec75ec3-df8e-44ea-b5d6-9f161a947d0a)

As I've thought, it's working as expected, just a name change

**Comment by darkrideroffate** [comment]
It seems that I haven't checked it enough and it's a problem on my end.
Thanks for checking it so quickly and sorry for making you worry.

**Comment by MrNaif2018** [comment]
If you need support with payments not detecting, you can join our community chats. You're welcome, no worries!
