### ISSUE TITLE
Nov 14 deadline: 2025 BCH upgrade approval

### ISSUE THREAD

**Issue by bitjson** [bitcart/bitcart#438]
Hello,

This is a formal request for approval from Bitcart regarding the May 2025 upgrade of Bitcoin Cash (BCH).

"CHIP-2021-05 VM Limits: Targeted Virtual Machine Limits" and "CHIP-2024-07 BigInt: High-Precision Arithmetic for Bitcoin Cash" have achieved the Cash Improvement Proposal (CHIP) milestones required to be locked in on November 15, 2024 and activated on May 15, 2025.

The CHIP contributors believe Bitcart is an important stakeholder in the Bitcoin Cash ecosystem. **Please respond by 12:00 UTC on November 14, 2024; non-responses will be considered "Abstain (Neutral)".**

<blockquote>

Does Bitcart approve of activating "CHIP-2021-05 VM Limits: Targeted Virtual Machine Limits" and "CHIP-2024-07 BigInt: High-Precision Arithmetic for Bitcoin Cash" in the May 2025 Upgrade to Bitcoin Cash (BCH)?

- Yes (Approve)
- No (Disapprove), or
- Abstain (Neutral)

Separate responses may also be given for each CHIP. To make a public statement explaining this decision, please provide it here (required for disapprovals): <br/><br/>

</blockquote>

For reference:

- VM Limits CHIP: https://github.com/bitjson/bch-vm-limits
- BigInt CHIP: https://github.com/bitjson/bch-bigint

Please let me know if you have any questions.

Thank you,<br/>Jason Dreyzehner<br/>VM Limits CHIP & BigInt CHIP Maintainer<br/>

**Comment by MrNaif2018** [comment]
Hi! Really sorry for not getting back to it earlier, was swomped with many tasks.
I approve both chips, it's probably too late to suggest changes anyway. Both proposals look good from initial glance, how it will work in practice I guess the chipnet testing can show with some stress tests. 
(it's not for comment to be added in the list)

Thank you for your continued improvements to BCH ecosystem!

**Comment by bitjson** [comment]
Great, thanks for your response @MrNaif2018!
