### ISSUE TITLE
Cannot accept payments from exchanges?

### ISSUE THREAD

**Issue by marcosolito** [bitcart/bitcart#439]
I was extremely happy to find an open source solution to my crypto checkout problem, but then I discovered that I cannot accept payments from users who send them via exchange.
This is not shown in any way in the demo and videos.
![Screenshot 2024-11-08 121426](https://github.com/user-attachments/assets/888d2d17-9221-4c96-88bc-ed9a409ca097)

My checkout show "Enter the address you will send from" this alert.
Is there any way to avoid this? I would like to simply accept the payment from whatever wallet it will come from.

Most users definitely want to pay from the Own Exchange in my case.

Please let me know.

**Comment by MrNaif2018** [comment]
GOSH, is AI on github now...

**Comment by MrNaif2018** [comment]
As to the actual issue: look, it's not that simple:
https://t.me/bitcart/20791

On the demo we have a plugin installed which fixes this issue, it's not ideal but the best fix for the issue
Plugin is in beta testing currently

**Comment by marcosolito** [comment]
Hello!
I didn't expect such a quick response! Thank you.

Which of the solutions in the post uses the plugin?
Can you also send it to me?

Actually, a temporary solution would be sufficient for me, one that can be optionally set up.
I've simply thought of ignoring completely from which address the payment comes. It's enough that the payment arrives. It can create confusion, but with a 15-minute time frame per invoice and quick approval, the confusion will be limited.
And, users often pay different prices!
Is there a way to quickly make a plugin to do this, or can you help me modify the code accordingly?

**Comment by MrNaif2018** [comment]
The plugin is currently limited to old-time bitcart users, you can join our community for updates when it becomes available
At the time that post was written plugin and that solution didn't exist. The post outlines solutions which don't require any spending from the merchant: unique amounts (used in older versions) and ask for from address (used currently). They are quite good but you should note that from address one doesn't support sending from exchanges. The unique amounts one can do that, but users and exchanges often send wrong amounts so it won't be detected at all

For top-up invoices you can create invoices with a price of 0, and then e.g. use https://api.bitcart.ai/#operation/update_payment_details_invoices__model_id__details_patch endpoint to set address to any value to remove address prompt

But from address solution is the best one we can get without merchants costs or complex logic like the one in beta plugin

**Comment by marcosolito** [comment]
I understand
I think the solution "unique amounts (used in older versions)" is better for me compared to the current one. Could you tell me which version to install to get it? Or if you have a quick fix to switch the current one to "unique amounts"?

**Comment by MrNaif2018** [comment]
As you've already got response in telegram chat, closing this for now.
